#!/usr/bin/env bash
set -euo pipefail

week_id="${WEEKLY_SYNTHESIS_WEEK_ID:-}"
if [[ -z "$week_id" ]]; then
  echo "WEEKLY_SYNTHESIS_WEEK_ID is required to publish the pull request" >&2
  exit 2
fi

branch="${WEEKLY_SYNTHESIS_BRANCH:-weekly-synthesis/${week_id}-${GITHUB_RUN_NUMBER:-local}}"

if [[ -z "${GH_TOKEN:-}" ]]; then
  echo "GH_TOKEN is required to publish the pull request" >&2
  exit 2
fi

git status --short
git add weekly-reports

if git diff --cached --quiet; then
  echo "No publishable Weekly Synthesis changes after applying the allowlist."
  exit 0
fi

git commit -m "Weekly synthesis ${week_id}"

git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
git push --set-upstream origin "$branch"

body_file="${RUNNER_TEMP:-/tmp}/weekly-synthesis-pr-${week_id}.md"
{
  echo "Automated weekly synthesis for ${week_id}."
  echo
  echo "This PR was generated by the scheduled GitHub Actions workflow."
  echo
  echo "Review checklist:"
  echo
  echo "- The report is under \`weekly-reports/${week_id}.md\`."
  echo "- The report synthesizes committed radar artifacts rather than new external discovery."
  echo "- Pattern movement, topic coverage, repeated candidates or signals, evidence gaps, and next-week focus are present."
  echo "- The next-week focus is one bounded action or an explicit no-action decision."
} > "$body_file"

gh pr create \
  --title "Weekly Synthesis ${week_id}" \
  --body-file "$body_file" \
  --base main \
  --head "$branch"
