#!/usr/bin/env bash
set -euo pipefail

run_date="${OPPORTUNITY_RADAR_RUN_DATE:-$(TZ=Europe/Moscow date +%F)}"
branch="${OPPORTUNITY_RADAR_BRANCH:-opportunity-radar/${run_date}-${GITHUB_RUN_NUMBER:-local}}"

if [[ -z "${GH_TOKEN:-}" ]]; then
  echo "GH_TOKEN is required to publish the pull request" >&2
  exit 2
fi

if git diff --quiet && git diff --cached --quiet; then
  echo "No Opportunity Radar changes to publish."
  exit 0
fi

git status --short
git add opportunity-interests.md opportunity-watchlist.yml opportunities.json opportunity-reports opportunities signals

if git diff --cached --quiet; then
  echo "No publishable Opportunity Radar changes after applying the allowlist."
  exit 0
fi

git commit -m "Opportunity radar report ${run_date}"

git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
git push --set-upstream origin "$branch"

body_file="${RUNNER_TEMP:-/tmp}/opportunity-radar-pr-${run_date}.md"
{
  echo "Automated Opportunity Radar run for ${run_date}."
  echo
  echo "This PR was generated by the manual GitHub Actions workflow."
  echo
  echo "Review checklist:"
  echo
  echo "- Signal ledger is present in \`opportunity-reports/${run_date}.md\`."
  echo "- Selected opportunities include market-specific evidence labels."
  echo "- Every selected opportunity ends in a testable offer with success and falsification thresholds."
  echo "- \`opportunities.json\` remains valid."
  echo "- Architecture Radar artifacts under \`reports/\`, \`repositories/\`, \`patterns/\`, and \`radar.json\` were not used for opportunity output."
} > "$body_file"

gh pr create \
  --title "Opportunity Radar ${run_date}" \
  --body-file "$body_file" \
  --base main \
  --head "$branch"
