#!/usr/bin/env bash
set -euo pipefail

run_date="${ARCHITECTURE_RADAR_RUN_DATE:-$(TZ=Europe/Moscow date +%F)}"
branch="${ARCHITECTURE_RADAR_BRANCH:-architecture-radar/${run_date}-${GITHUB_RUN_NUMBER:-local}}"

if [[ -z "${GH_TOKEN:-}" ]]; then
  echo "GH_TOKEN is required to publish the pull request" >&2
  exit 2
fi

git status --short
git add README.md interests.md radar.json reports repositories patterns

if git diff --cached --quiet; then
  echo "No publishable Architecture Radar changes after applying the allowlist."
  exit 0
fi

git commit -m "Architecture radar report ${run_date}"

git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
git push --set-upstream origin "$branch"

body_file="${RUNNER_TEMP:-/tmp}/architecture-radar-pr-${run_date}.md"
{
  echo "Automated Architecture Radar run for ${run_date}."
  echo
  echo "This PR was generated by the scheduled GitHub Actions workflow."
  echo
  echo "Review checklist:"
  echo
  echo "- Candidate ledger is present in \`reports/${run_date}.md\`."
  echo "- Deep reviews are pinned to full commit SHAs."
  echo "- Claims distinguish source evidence, tests, maintainer statements, interpretations, and hypotheses."
  echo "- New patterns are justified by the evidence threshold."
  echo "- \`radar.json\` remains valid."
} > "$body_file"

gh pr create \
  --title "Architecture Radar ${run_date}" \
  --body-file "$body_file" \
  --base main \
  --head "$branch"
